### ISSUE TITLE
When clicking the "load" link next to the UK Power box i get "tariff id invalid"

### ISSUE THREAD

**Issue by jamiemax** [jamiemax/optimisebills#2]
This happens on client manager 2 - on client manager 3 nothing happens at all

**Comment by iddmaxwell** [comment]
which client?  Some tariffs don't work.  CM3 doesn't respond if it's not working whereas CM2 does at least give a 'tariff id invalid'

**Comment by jamiemax** [comment]
ah ok so another one i just tried is working. i'll keep working through them and i'll close this if the other work

**Comment by jamiemax** [comment]
actually now it's gone back to saying tariff id invalid on all of them. the one i thought was working created a link but when i tried to open the link it said "page not found" on UK Power
