### ISSUE TITLE
Deleted tariffs reappearing - e.g. Scot Power and Swalec

### ISSUE THREAD

**Issue by iddmaxwell** [jamiemax/optimisebills#23]
I've deleted - changed status - several tariffs previously and they keep reappearing in the list.
one is 
Swalec SSE 1 Year Fixed v6 Paperless Billing
another is
Scottish Power Online Fixed Price Energy June 2017
also 
Flow Connect 5
maybe others

**Comment by Will-Newton** [comment]
Think this is resolved because none of the mentioned tariffs are showing up as active.
