### ISSUE TITLE
tariffs on UK Power are being missed in the loading script

### ISSUE THREAD

**Issue by iddmaxwell** [jamiemax/optimisebills#24]
tariffs missed include
Avro -all
GB Energy - Crystal
Is this because they are not 'switchable'?
However the api does give the option to return all available tariffs.  the spec implies that all the same rate information is available for these tariffs,

**Comment by iddmaxwell** [comment]
Tariffs are now appearing but there are still some issues to resolve: 

I’ve been looking at this some more and found discrepancies between the UK Power comparison page and our OB comparison page.

The client is Lockley

https://optimisebills.com/test/Admin/BatchTariffComparison.aspx?U=5b20377f-9e96-4bf9-853e-f811b087ffb5
UK Power link: 
https://www.ukpower.co.uk/home_energy/compare/electricity/SE5ZUCED?r=srpi

one issue I’ve found is that the Elec only unit rates appear to be wrong – for SSE Paperless v8.  They appear to be using the Elec Only – Econ 7 rates instead of Elec Only.  Because the % overnight is set to 0%, this causes the tariff to be overpriced.  

This might be the same issue for all Elec only.  It’s difficult for me to check because UK Power doesn’t show rates for tariffs you can’t switch to.  

Also questions below (copied from recent email) 
I’ve numbered the points below so you can respond more easily 

1.	I can see a lot more tariffs now so it looks as if it’s pretty much working which is great.  Not all are available today though.  What date did you carry out the load?  Npower’s new September tariffs launched 10 August are not showing for example. 

2.	Looking at this I’m trying to see why there are differences.  Some tariffs are quite a bit more than £2 out so I guess you didn’t check them all.  Which client and which area did you use for the comparison? Which tariffs did you check?  

3.	Flow Connect 8 (Oct 17) is not showing in the OB list. It’s not a new tariff.  It’s in the tariff table for many areas. I don’t know if it is in the area for the client you tested because I don’t know which area you used.  

4.	Does anything happen to existing ‘Active’ tariffs?  I.e. do they stay there until I manually reset them to ‘in use’ or do you automatically set them to ‘in use’ before the load takes place?  It appears that there are some ‘old’ tariffs still showing.  

5.	Do you get the discount information in the API feed?  And if so is this in the tariff table description field?  I can’t find an example otherwise I’d look for it myself.  

6.	Some of the new suppliers don’t appear in the Tariff Table drop down so I can’t search for or do anything with them.  Places & People and Octopus are two examples.  Bristol Energy and So Energy too.   Is this always going to be a manual process? If so, is there a check you can put in to identify new suppliers?  

7.	Are you now sorting out the loading of new Standard and variable rates?  When can I expect something on this?  

Can you let me know? 
Thanks 
Ian

Ian Maxwell
M: +44 (0)7866 767630

**Comment by iddmaxwell** [comment]
Hi Will
I’ve been looking at this some more and found discrepancies between the UK Power comparison page and our OB comparison page.

The client is Lockley

https://optimisebills.com/test/Admin/BatchTariffComparison.aspx?U=5b20377f-9e96-4bf9-853e-f811b087ffb5
UK Power link: 
https://www.ukpower.co.uk/home_energy/compare/electricity/SE5ZUCED?r=srpi

one issue I’ve found is that the Elec only unit rates appear to be wrong – for SSE Paperless v8.  They appear to be using the Elec Only – Econ 7 rates instead of Elec Only.  Because the % overnight is set to 0%, this causes the tariff to be overpriced.  

This might be the same issue for all Elec only.  It’s difficult for me to check because UK Power doesn’t show rates for tariffs you can’t switch to.  

Can you please look at this asap and also the points below?  

Thanks
Ian

Ian Maxwell
M: +44 (0)7866 767630

From: Ian Maxwell 
Sent: 15 August 2016 16:19
To: William Newton <williamnewton2005@yahoo.co.uk>
Cc: Ian Maxwell <ian.maxwell@srpi.net>
Subject: RE: notification - issue wth new AVro tariffs - testing

Hi Will
I’ve numbered the points below so you can respond more easily 

1.	I can see a lot more tariffs now so it looks as if it’s pretty much working which is great.  Not all are available today though.  What date did you carry out the load?  Npower’s new September tariffs launched 10 August are not showing for example. 

2.	Looking at this I’m trying to see why there are differences.  Some tariffs are quite a bit more than £2 out so I guess you didn’t check them all.  Which client and which area did you use for the comparison? Which tariffs did you check?  

3.	Flow Connect 8 (Oct 17) is not showing in the OB list. It’s not a new tariff.  It’s in the tariff table for many areas. I don’t know if it is in the area for the client you tested because I don’t know which area you used.  

4.	Does anything happen to existing ‘Active’ tariffs?  I.e. do they stay there until I manually reset them to ‘in use’ or do you automatically set them to ‘in use’ before the load takes place?  It appears that there are some ‘old’ tariffs still showing.  

5.	Do you get the discount information in the API feed?  And if so is this in the tariff table description field?  I can’t find an example otherwise I’d look for it myself.  

6.	Some of the new suppliers don’t appear in the Tariff Table drop down so I can’t search for or do anything with them.  Places & People and Octopus are two examples.  Bristol Energy and So Energy too.   Is this always going to be a manual process? If so, is there a check you can put in to identify new suppliers?  

7.	Are you now sorting out the loading of new Standard and variable rates?  When can I expect something on this?  

Can you let me know? 
Thanks 
Ian

Ian Maxwell
M: +44 (0)7866 767630

**Comment by iddmaxwell** [comment]
The latest one I've found missing is 
E.ON Energy Saver Fixed 1 Year v1 (Paperless Billing)
I don't know when the load script is run (except that you said you ran it last week - c. 20th September) but this tariff was available then I believe and it hasn't been loaded.  
To avoid these queries we need to have 
1. the schedule for the tariff load
2. the list of tariffs loaded at that time (we spoke about having a list - you said you could download one to Excel quite easily). 
Note that if a tariff is launched and withdrawn between scripts then it will be completely missed.

**Comment by Will-Newton** [comment]
That tariff appeared midway through the previous load so it's there in a few area/types. The rest are being added in the current load. Started it on Sunday, it should be finished tomorrow. I'll send through a list of the latest tariffs when it has completed loading.

**Comment by iddmaxwell** [comment]
ok - when will the tariff load process be run regularly?
