### ISSUE TITLE
Some tariffs have not been loaded after the changes made 23/7/2017

### ISSUE THREAD

**Issue by iddmaxwell** [jamiemax/optimisebills#27]
https://www.ukpower.co.uk/home_energy/compare/electricity/8KVVY34F?r=srpi
top two tariffs FU and Scottish Power are not in the SWEB region. only in Manweb, Southern, Norweb, Eastern.
They should be in all regions.

**Comment by Will-Newton** [comment]
I think this was resolved because First Fixed September 2017 v3 is in the tariff table.
