### ISSUE TITLE
First Utility tariffs all seem to be missing. Disappeared from tariff manager! 

### ISSUE THREAD

**Issue by iddmaxwell** [jamiemax/optimisebills#33]
Searched in tariff manager for all regions, all types, First Utility supplier, all statuses.
No results.
Enquiry earlier this week from Paul Metcalf who said that only First Variable was an option on the screen. Even that seems to have gone now.
have they been deleted? presumably not, but why are they not appearing?  
I can't see any other tariffs in the energy record editor either.

**Comment by iddmaxwell** [comment]
The tariffs added to UK Power since around 30th August are missing from tariff manager. 
Emailed Will today. There should be a regular at least weekly load of tariffs.

**Comment by Will-Newton** [comment]
Think I resolved this previously, as they are appearing in the tariff manager now.

**Comment by iddmaxwell** [comment]
how often and on what date is the tariff table updated?  There is a new First Utility tariff and other tariffs today that are not yet in the tariff table.  When will these be added?
