### ISSUE TITLE
first utility logo missing causing server errors, e.g. on Comparison New or just returning to CM2 page

### ISSUE THREAD

**Issue by iddmaxwell** [jamiemax/optimisebills#34]
Server Error in '/' Application.

'~\Images\first:utility.gif' is not a valid virtual path. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.Web.HttpException: '~\Images\first:utility.gif' is not a valid virtual path.

Source Error: 

 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 

[HttpException (0x80004005): '~\Images\first:utility.gif' is not a valid virtual path.]
   System.Web.Util.UrlPath.CheckValidVirtualPath(String path) +11175146
   System.Web.Util.UrlPath.Combine(String appPath, String basepath, String relative) +122
   System.Web.UI.Control.ResolveClientUrl(String relativeUrl) +212
   System.Web.UI.WebControls.Image.AddAttributesToRender(HtmlTextWriter writer) +73
   System.Web.UI.WebControls.WebControl.RenderBeginTag(HtmlTextWriter writer) +27
   System.Web.UI.WebControls.WebControl.Render(HtmlTextWriter writer) +27
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +240
   System.Web.UI.WebControls.WebControl.RenderContents(HtmlTextWriter writer) +13
   System.Web.UI.WebControls.DataListItem.RenderItemInternal(HtmlTextWriter writer, Boolean extractRows, Boolean tableLayout) +59
   System.Web.UI.WebControls.RepeatInfo.RenderVerticalRepeater(HtmlTextWriter writer, IRepeatInfoUser user, Style controlStyle, WebControl baseControl) +707
   System.Web.UI.WebControls.DataList.RenderContents(HtmlTextWriter writer) +252
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +240
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +240
   System.Web.UI.UpdatePanel.RenderChildren(HtmlTextWriter writer) +288
   System.Web.UI.UpdatePanel.Render(HtmlTextWriter writer) +53
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +240
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +240
   System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer) +253
   System.Web.UI.HtmlControls.HtmlForm.Render(HtmlTextWriter output) +87
   System.Web.UI.HtmlControls.HtmlForm.RenderControl(HtmlTextWriter writer) +53
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +240
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +240
   System.Web.UI.Page.Render(HtmlTextWriter writer) +38
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +11140667
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +4240

**Comment by iddmaxwell** [comment]
I was updating the tariff for Neil Bickley to a different FU tariff than he already had.  Now I can't go back to his record to do anything.

**Comment by Will-Newton** [comment]
Fixed
