### ISSUE TITLE
tariff report screen is showing exit fees are applicable when they are not

### ISSUE THREAD

**Issue by iddmaxwell** [jamiemax/optimisebills#37]
e.g. FU tariff ending 31st October 2016 is showing with exit fees applicable as at 26th September.  Is the cut-off set to 30 days just now? 
Can we change it to 41 days prior to the tariff end date?

**Comment by Will-Newton** [comment]
Please can you put a link on for this? If you can put links on these types of issue in future, it's quicker to work back from an example.

**Comment by iddmaxwell** [comment]
This is a link with the current tariff that has already been updated for the client - not the original tariff that ended in October 2016. 
https://optimisebills.com/Account/LinkReport.aspx?U=20144c29-3938-47b9-97cb-1918ce519e9f&V=0&S=Dual+Fuel

**Comment by Will-Newton** [comment]
I don't think there is any date based processing. It's just looking at exit fees on the energy record from what I can see.

**Comment by iddmaxwell** [comment]
There is date based processing.  I amended the end date to 30/09/2016 so in a few days time and the system automatically uses the standard tariff which has no cancellation fee. 
https://optimisebills.com/Account/LinkReport.aspx?U=20144c29-3938-47b9-97cb-1918ce519e9f&V=0&S=Dual+Fuel&standardTariff=true

**Comment by iddmaxwell** [comment]
have you changed it already? It seems to be working as I would hope!

**Comment by Will-Newton** [comment]
The standard tariff processing is set to 35 days from the contract end date.

**Comment by iddmaxwell** [comment]
Ah just checked it worked for over 30. Can you update it to 41 easily?

**Comment by Will-Newton** [comment]
That should be set to 41 now.
