### ISSUE TITLE
Scottish Power logo missing from CM2 page - see PHilip Truppin

### ISSUE THREAD

**Issue by iddmaxwell** [jamiemax/optimisebills#39]
Current tariff shows SP logo correctly.
comparison record doesn't show it. 
also not shown on Comparison - new screen
https://optimisebills.com/test/Admin/BatchTariffComparison.aspx?U=a845958d-99b6-4ca6-bcfa-897868bec5ba

**Comment by Will-Newton** [comment]
This is fixed now.
